### ISSUE TITLE
Updated?

### ISSUE THREAD

**Issue by gaurav-gogia** [olliephillips/sett#1]
This is really good ^.^

I was just wondering if you have plans on keeping it updated along with BadgerDB?

I could try and contribute to the code as and when time permits if you're accepting contribution ^.^

**Comment by olliephillips** [comment]
I'd no idea there had been so many releases TBH. Looks like I got on BadgerDB early on. However, briefly looking through the release docs I couldn't see anything that would break the sett API, but perhaps you have spotted something, or run it and found it breaks?  Happy to take PRs but maybe it is as simple as removing the hard reference to v0.9.0 in the README.md at this time? Happy to hear your thoughts.

**Comment by gaurav-gogia** [comment]
I was just getting started with BadgerDB so have only done basic CRUD stuff. I'm gonna try a few more things. Will update if I find something :)

**Comment by azilber** [comment]
I just tried running the most basic example, and got this:

`# github.com/olliephillips/sett
../../github.com/olliephillips/sett/sett.go:72:12: assignment mismatch: 2 variables but 1 values
../../github.com/olliephillips/sett/sett.go:72:24: not enough arguments in call to item.Value
	have ()
	want (func([]byte) error)
../../github.com/olliephillips/sett/sett.go:151:9: assignment mismatch: 2 variables but 1 values
../../github.com/olliephillips/sett/sett.go:151:22: not enough arguments in call to item.Value
	have ()
	want (func([]byte) error)
../../github.com/olliephillips/sett/sett.go:203:13`

**Comment by olliephillips** [comment]
I've just checked again and the item.Value API has indeed changed in BadgerDB,  so this library is currently broken. I'll look at this as soon as I can

**Comment by olliephillips** [comment]
Actually, it looks like item.Value() api will be a breaking change from v2.0.0. Release v1.5.4 still supports the API and should not error. I'm going to add tests which are overdue and modules support to fix the version to 1.5.4 release. I'll fix any problems I find, but I'm unlikely to get to a rewrite to support v2.0.0 any time soon. Help on support for v2 more than welcome.

**Comment by olliephillips** [comment]
Just pushed. Deprecated the `purge` method from Sett API. It's still there, but now returns nil error, so should not break any existing code. There's a test suite with 95% coverage and modules support. Let me know if any problems. Closing this.

**Comment by azilber** [comment]
I reverted BadgerDB to v1.5.4 and got this:

```
# github.com/olliephillips/sett
../../github.com/olliephillips/sett/sett.go:203:13: s.db.PurgeOlderVersions undefined (type *badger.DB has no field or method PurgeOlderVersions)

```
v1.5.0 works.  Anything after it, has the error above.

**Comment by azilber** [comment]
Oh sorry, haven't checked your fix..

**Comment by azilber** [comment]
Yay!  All fixed 👍

**Comment by olliephillips** [comment]
> Oh sorry, haven't checked your fix..

> Yay! All fixed 👍

No worries, thanks for your testing, and interest in this package. Appreciated :)
