### ISSUE TITLE
 not enough arguments in call to item.Value

### ISSUE THREAD

**Issue by tegk** [olliephillips/sett#2]
```
# github.com/olliephillips/sett
..\github.com\olliephillips\sett\sett.go:72:12: assignment mismatch: 2 variables but 1 values
..\github.com\olliephillips\sett\sett.go:72:24: not enough arguments in call to item.Value
        have ()
        want (func([]byte) error)
..\github.com\olliephillips\sett\sett.go:151:9: assignment mismatch: 2 variables but 1 values
..\github.com\olliephillips\sett\sett.go:151:22: not enough arguments in call to item.Value
        have ()
        want (func([]byte) error)
```

**Comment by olliephillips** [comment]
That error looks like v2 tip of Badger. For now you need to use sett with a release, the latest of which is v1.5.3. Sett is built and tested against the v1 api

**Comment by tegk** [comment]
Could you estimate how much work it is to support v2? I am happy to contribute some code.

**Comment by olliephillips** [comment]
While I don't think the v2 badger API has changed drastically so far, it is fluid I imagine since as yet there is no v2 release. I can't give you estimates as I'm not up to speed with it TBH. But I think it prudent to wait for the release, unless there are v2 features you absolutely must have now.
